//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PogodaClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PogodaResult", Namespace="http://schemas.datacontract.org/2004/07/PogodaService")]
    [System.SerializableAttribute()]
    public partial class PogodaResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemperatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.TemperatureField, value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyPogoda")]
    public interface IMyPogoda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyPogoda/GetPogodaByCity", ReplyAction="http://tempuri.org/IMyPogoda/GetPogodaByCityResponse")]
        PogodaClient.ServiceReference1.PogodaResult[] GetPogodaByCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyPogoda/GetPogodaByCity", ReplyAction="http://tempuri.org/IMyPogoda/GetPogodaByCityResponse")]
        System.IAsyncResult BeginGetPogodaByCity(string city, System.AsyncCallback callback, object asyncState);
        
        PogodaClient.ServiceReference1.PogodaResult[] EndGetPogodaByCity(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyPogodaChannel : PogodaClient.ServiceReference1.IMyPogoda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPogodaByCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPogodaByCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PogodaClient.ServiceReference1.PogodaResult[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PogodaClient.ServiceReference1.PogodaResult[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyPogodaClient : System.ServiceModel.ClientBase<PogodaClient.ServiceReference1.IMyPogoda>, PogodaClient.ServiceReference1.IMyPogoda {
        
        private BeginOperationDelegate onBeginGetPogodaByCityDelegate;
        
        private EndOperationDelegate onEndGetPogodaByCityDelegate;
        
        private System.Threading.SendOrPostCallback onGetPogodaByCityCompletedDelegate;
        
        public MyPogodaClient() {
        }
        
        public MyPogodaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyPogodaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPogodaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPogodaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetPogodaByCityCompletedEventArgs> GetPogodaByCityCompleted;
        
        public PogodaClient.ServiceReference1.PogodaResult[] GetPogodaByCity(string city) {
            return base.Channel.GetPogodaByCity(city);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPogodaByCity(string city, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPogodaByCity(city, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PogodaClient.ServiceReference1.PogodaResult[] EndGetPogodaByCity(System.IAsyncResult result) {
            return base.Channel.EndGetPogodaByCity(result);
        }
        
        private System.IAsyncResult OnBeginGetPogodaByCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string city = ((string)(inValues[0]));
            return this.BeginGetPogodaByCity(city, callback, asyncState);
        }
        
        private object[] OnEndGetPogodaByCity(System.IAsyncResult result) {
            PogodaClient.ServiceReference1.PogodaResult[] retVal = this.EndGetPogodaByCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPogodaByCityCompleted(object state) {
            if ((this.GetPogodaByCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPogodaByCityCompleted(this, new GetPogodaByCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPogodaByCityAsync(string city) {
            this.GetPogodaByCityAsync(city, null);
        }
        
        public void GetPogodaByCityAsync(string city, object userState) {
            if ((this.onBeginGetPogodaByCityDelegate == null)) {
                this.onBeginGetPogodaByCityDelegate = new BeginOperationDelegate(this.OnBeginGetPogodaByCity);
            }
            if ((this.onEndGetPogodaByCityDelegate == null)) {
                this.onEndGetPogodaByCityDelegate = new EndOperationDelegate(this.OnEndGetPogodaByCity);
            }
            if ((this.onGetPogodaByCityCompletedDelegate == null)) {
                this.onGetPogodaByCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPogodaByCityCompleted);
            }
            base.InvokeAsync(this.onBeginGetPogodaByCityDelegate, new object[] {
                        city}, this.onEndGetPogodaByCityDelegate, this.onGetPogodaByCityCompletedDelegate, userState);
        }
    }
}
