//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PogodaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Pogoda = new HashSet<Pogoda>();
        }
    
        public int LocationID { get; set; }
        public string country { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<Pogoda> Pogoda { get; set; }
    }
}
