//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_BankClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBankSerevice")]
    public interface IBankSerevice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSerevice/ToDeposit", ReplyAction="http://tempuri.org/IBankSerevice/ToDepositResponse")]
        void ToDeposit(double sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSerevice/ToDeposit", ReplyAction="http://tempuri.org/IBankSerevice/ToDepositResponse")]
        System.Threading.Tasks.Task ToDepositAsync(double sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSerevice/GetBalance", ReplyAction="http://tempuri.org/IBankSerevice/GetBalanceResponse")]
        double GetBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSerevice/GetBalance", ReplyAction="http://tempuri.org/IBankSerevice/GetBalanceResponse")]
        System.Threading.Tasks.Task<double> GetBalanceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankSereviceChannel : WCF_BankClient.ServiceReference1.IBankSerevice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankSereviceClient : System.ServiceModel.ClientBase<WCF_BankClient.ServiceReference1.IBankSerevice>, WCF_BankClient.ServiceReference1.IBankSerevice {
        
        public BankSereviceClient() {
        }
        
        public BankSereviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankSereviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankSereviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankSereviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ToDeposit(double sum) {
            base.Channel.ToDeposit(sum);
        }
        
        public System.Threading.Tasks.Task ToDepositAsync(double sum) {
            return base.Channel.ToDepositAsync(sum);
        }
        
        public double GetBalance() {
            return base.Channel.GetBalance();
        }
        
        public System.Threading.Tasks.Task<double> GetBalanceAsync() {
            return base.Channel.GetBalanceAsync();
        }
    }
}
